# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC+MVVM_01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RAC+MVVM_01
  pod 'ReactiveCocoa', '~> 2.5.0'
  target 'RAC+MVVM_01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC+MVVM_01UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
